// Generated by gencpp from file me495_hw1/ME495Pub.msg
// DO NOT EDIT!


#ifndef ME495_HW1_MESSAGE_ME495PUB_H
#define ME495_HW1_MESSAGE_ME495PUB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace me495_hw1
{
template <class ContainerAllocator>
struct ME495Pub_
{
  typedef ME495Pub_<ContainerAllocator> Type;

  ME495Pub_()
    : header()
    , time(0.0)
    , configuration(0.0)  {
    }
  ME495Pub_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time(0.0)
    , configuration(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _time_type;
  _time_type time;

   typedef float _configuration_type;
  _configuration_type configuration;




  typedef boost::shared_ptr< ::me495_hw1::ME495Pub_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::me495_hw1::ME495Pub_<ContainerAllocator> const> ConstPtr;

}; // struct ME495Pub_

typedef ::me495_hw1::ME495Pub_<std::allocator<void> > ME495Pub;

typedef boost::shared_ptr< ::me495_hw1::ME495Pub > ME495PubPtr;
typedef boost::shared_ptr< ::me495_hw1::ME495Pub const> ME495PubConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::me495_hw1::ME495Pub_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::me495_hw1::ME495Pub_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace me495_hw1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'me495_hw1': ['/home/josmiranda/ros/src/me495_hw1/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::me495_hw1::ME495Pub_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::me495_hw1::ME495Pub_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me495_hw1::ME495Pub_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me495_hw1::ME495Pub_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me495_hw1::ME495Pub_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me495_hw1::ME495Pub_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::me495_hw1::ME495Pub_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91983dfb08bae7741ea33f6281cab302";
  }

  static const char* value(const ::me495_hw1::ME495Pub_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91983dfb08bae774ULL;
  static const uint64_t static_value2 = 0x1ea33f6281cab302ULL;
};

template<class ContainerAllocator>
struct DataType< ::me495_hw1::ME495Pub_<ContainerAllocator> >
{
  static const char* value()
  {
    return "me495_hw1/ME495Pub";
  }

  static const char* value(const ::me495_hw1::ME495Pub_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::me495_hw1::ME495Pub_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 time\n\
float32 configuration\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::me495_hw1::ME495Pub_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::me495_hw1::ME495Pub_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time);
      stream.next(m.configuration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ME495Pub_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::me495_hw1::ME495Pub_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::me495_hw1::ME495Pub_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
    s << indent << "configuration: ";
    Printer<float>::stream(s, indent + "  ", v.configuration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ME495_HW1_MESSAGE_ME495PUB_H
