// Generated by gencpp from file me495_hw1/ME495Srv.msg
// DO NOT EDIT!


#ifndef ME495_HW1_MESSAGE_ME495SRV_H
#define ME495_HW1_MESSAGE_ME495SRV_H

#include <ros/service_traits.h>


#include <me495_hw1/ME495SrvRequest.h>
#include <me495_hw1/ME495SrvResponse.h>


namespace me495_hw1
{

struct ME495Srv
{

typedef ME495SrvRequest Request;
typedef ME495SrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ME495Srv
} // namespace me495_hw1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::me495_hw1::ME495Srv > {
  static const char* value()
  {
    return "32801ee1a02c70a4c37e1dd07ac2075b";
  }

  static const char* value(const ::me495_hw1::ME495Srv&) { return value(); }
};

template<>
struct DataType< ::me495_hw1::ME495Srv > {
  static const char* value()
  {
    return "me495_hw1/ME495Srv";
  }

  static const char* value(const ::me495_hw1::ME495Srv&) { return value(); }
};


// service_traits::MD5Sum< ::me495_hw1::ME495SrvRequest> should match 
// service_traits::MD5Sum< ::me495_hw1::ME495Srv > 
template<>
struct MD5Sum< ::me495_hw1::ME495SrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::me495_hw1::ME495Srv >::value();
  }
  static const char* value(const ::me495_hw1::ME495SrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::me495_hw1::ME495SrvRequest> should match 
// service_traits::DataType< ::me495_hw1::ME495Srv > 
template<>
struct DataType< ::me495_hw1::ME495SrvRequest>
{
  static const char* value()
  {
    return DataType< ::me495_hw1::ME495Srv >::value();
  }
  static const char* value(const ::me495_hw1::ME495SrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::me495_hw1::ME495SrvResponse> should match 
// service_traits::MD5Sum< ::me495_hw1::ME495Srv > 
template<>
struct MD5Sum< ::me495_hw1::ME495SrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::me495_hw1::ME495Srv >::value();
  }
  static const char* value(const ::me495_hw1::ME495SrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::me495_hw1::ME495SrvResponse> should match 
// service_traits::DataType< ::me495_hw1::ME495Srv > 
template<>
struct DataType< ::me495_hw1::ME495SrvResponse>
{
  static const char* value()
  {
    return DataType< ::me495_hw1::ME495Srv >::value();
  }
  static const char* value(const ::me495_hw1::ME495SrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ME495_HW1_MESSAGE_ME495SRV_H
